### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [derekmccool/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by derekmccool** [comment]
I added the meta tag and updated it on Git, let me know what you think.

Thanks!

**Comment by Mikeysax** [comment]
:+1:
